// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: service/service.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateUserServiceProfileRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	UserId               string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ServicingCategoryId  string                 `protobuf:"bytes,2,opt,name=servicing_category_id,json=servicingCategoryId,proto3" json:"servicing_category_id,omitempty"`
	ServicingCityId      string                 `protobuf:"bytes,3,opt,name=servicing_city_id,json=servicingCityId,proto3" json:"servicing_city_id,omitempty"`
	ServicingLocation    string                 `protobuf:"bytes,4,opt,name=servicing_location,json=servicingLocation,proto3" json:"servicing_location,omitempty"`
	ServicingDistrictIds []string               `protobuf:"bytes,5,rep,name=servicing_district_ids,json=servicingDistrictIds,proto3" json:"servicing_district_ids,omitempty"`
	ServicingKeywords    []string               `protobuf:"bytes,6,rep,name=servicing_keywords,json=servicingKeywords,proto3" json:"servicing_keywords,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CreateUserServiceProfileRequest) Reset() {
	*x = CreateUserServiceProfileRequest{}
	mi := &file_service_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserServiceProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserServiceProfileRequest) ProtoMessage() {}

func (x *CreateUserServiceProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserServiceProfileRequest.ProtoReflect.Descriptor instead.
func (*CreateUserServiceProfileRequest) Descriptor() ([]byte, []int) {
	return file_service_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserServiceProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateUserServiceProfileRequest) GetServicingCategoryId() string {
	if x != nil {
		return x.ServicingCategoryId
	}
	return ""
}

func (x *CreateUserServiceProfileRequest) GetServicingCityId() string {
	if x != nil {
		return x.ServicingCityId
	}
	return ""
}

func (x *CreateUserServiceProfileRequest) GetServicingLocation() string {
	if x != nil {
		return x.ServicingLocation
	}
	return ""
}

func (x *CreateUserServiceProfileRequest) GetServicingDistrictIds() []string {
	if x != nil {
		return x.ServicingDistrictIds
	}
	return nil
}

func (x *CreateUserServiceProfileRequest) GetServicingKeywords() []string {
	if x != nil {
		return x.ServicingKeywords
	}
	return nil
}

type CreateUserServiceProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserServiceProfileResponse) Reset() {
	*x = CreateUserServiceProfileResponse{}
	mi := &file_service_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserServiceProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserServiceProfileResponse) ProtoMessage() {}

func (x *CreateUserServiceProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserServiceProfileResponse.ProtoReflect.Descriptor instead.
func (*CreateUserServiceProfileResponse) Descriptor() ([]byte, []int) {
	return file_service_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserServiceProfileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateUserServiceProfileResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_service_service_proto protoreflect.FileDescriptor

const file_service_service_proto_rawDesc = "" +
	"\n" +
	"\x15service/service.proto\x12\aservice\"\xae\x02\n" +
	"\x1fCreateUserServiceProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x122\n" +
	"\x15servicing_category_id\x18\x02 \x01(\tR\x13servicingCategoryId\x12*\n" +
	"\x11servicing_city_id\x18\x03 \x01(\tR\x0fservicingCityId\x12-\n" +
	"\x12servicing_location\x18\x04 \x01(\tR\x11servicingLocation\x124\n" +
	"\x16servicing_district_ids\x18\x05 \x03(\tR\x14servicingDistrictIds\x12-\n" +
	"\x12servicing_keywords\x18\x06 \x03(\tR\x11servicingKeywords\"V\n" +
	" CreateUserServiceProfileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x81\x01\n" +
	"\x0eServiceService\x12o\n" +
	"\x18CreateUserServiceProfile\x12(.service.CreateUserServiceProfileRequest\x1a).service.CreateUserServiceProfileResponseB1Z/github.com/ozdemirmurat2000/takas-proto/serviceb\x06proto3"

var (
	file_service_service_proto_rawDescOnce sync.Once
	file_service_service_proto_rawDescData []byte
)

func file_service_service_proto_rawDescGZIP() []byte {
	file_service_service_proto_rawDescOnce.Do(func() {
		file_service_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_service_proto_rawDesc), len(file_service_service_proto_rawDesc)))
	})
	return file_service_service_proto_rawDescData
}

var file_service_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_service_service_proto_goTypes = []any{
	(*CreateUserServiceProfileRequest)(nil),  // 0: service.CreateUserServiceProfileRequest
	(*CreateUserServiceProfileResponse)(nil), // 1: service.CreateUserServiceProfileResponse
}
var file_service_service_proto_depIdxs = []int32{
	0, // 0: service.ServiceService.CreateUserServiceProfile:input_type -> service.CreateUserServiceProfileRequest
	1, // 1: service.ServiceService.CreateUserServiceProfile:output_type -> service.CreateUserServiceProfileResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_service_proto_init() }
func file_service_service_proto_init() {
	if File_service_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_service_proto_rawDesc), len(file_service_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_service_proto_goTypes,
		DependencyIndexes: file_service_service_proto_depIdxs,
		MessageInfos:      file_service_service_proto_msgTypes,
	}.Build()
	File_service_service_proto = out.File
	file_service_service_proto_goTypes = nil
	file_service_service_proto_depIdxs = nil
}
