// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: category/category.proto

package category

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckCategoryRequest) Reset() {
	*x = CheckCategoryRequest{}
	mi := &file_category_category_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckCategoryRequest) ProtoMessage() {}

func (x *CheckCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_category_category_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckCategoryRequest.ProtoReflect.Descriptor instead.
func (*CheckCategoryRequest) Descriptor() ([]byte, []int) {
	return file_category_category_proto_rawDescGZIP(), []int{0}
}

func (x *CheckCategoryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CheckCategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckCategoryResponse) Reset() {
	*x = CheckCategoryResponse{}
	mi := &file_category_category_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckCategoryResponse) ProtoMessage() {}

func (x *CheckCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_category_category_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckCategoryResponse.ProtoReflect.Descriptor instead.
func (*CheckCategoryResponse) Descriptor() ([]byte, []int) {
	return file_category_category_proto_rawDescGZIP(), []int{1}
}

func (x *CheckCategoryResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

var File_category_category_proto protoreflect.FileDescriptor

const file_category_category_proto_rawDesc = "" +
	"\n" +
	"\x17category/category.proto\x12\bcategory\"&\n" +
	"\x14CheckCategoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"/\n" +
	"\x15CheckCategoryResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists2c\n" +
	"\x0fCategoryService\x12P\n" +
	"\rCheckCategory\x12\x1e.category.CheckCategoryRequest\x1a\x1f.category.CheckCategoryResponseB6Z4github.com/ozdemirmurat2000/takas-app/proto/categoryb\x06proto3"

var (
	file_category_category_proto_rawDescOnce sync.Once
	file_category_category_proto_rawDescData []byte
)

func file_category_category_proto_rawDescGZIP() []byte {
	file_category_category_proto_rawDescOnce.Do(func() {
		file_category_category_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_category_category_proto_rawDesc), len(file_category_category_proto_rawDesc)))
	})
	return file_category_category_proto_rawDescData
}

var file_category_category_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_category_category_proto_goTypes = []any{
	(*CheckCategoryRequest)(nil),  // 0: category.CheckCategoryRequest
	(*CheckCategoryResponse)(nil), // 1: category.CheckCategoryResponse
}
var file_category_category_proto_depIdxs = []int32{
	0, // 0: category.CategoryService.CheckCategory:input_type -> category.CheckCategoryRequest
	1, // 1: category.CategoryService.CheckCategory:output_type -> category.CheckCategoryResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_category_category_proto_init() }
func file_category_category_proto_init() {
	if File_category_category_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_category_category_proto_rawDesc), len(file_category_category_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_category_category_proto_goTypes,
		DependencyIndexes: file_category_category_proto_depIdxs,
		MessageInfos:      file_category_category_proto_msgTypes,
	}.Build()
	File_category_category_proto = out.File
	file_category_category_proto_goTypes = nil
	file_category_category_proto_depIdxs = nil
}
