// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: location/location.proto

package location

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDistrictsByIDSRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDistrictsByIDSRequest) Reset() {
	*x = GetDistrictsByIDSRequest{}
	mi := &file_location_location_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDistrictsByIDSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDistrictsByIDSRequest) ProtoMessage() {}

func (x *GetDistrictsByIDSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_location_location_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDistrictsByIDSRequest.ProtoReflect.Descriptor instead.
func (*GetDistrictsByIDSRequest) Descriptor() ([]byte, []int) {
	return file_location_location_proto_rawDescGZIP(), []int{0}
}

func (x *GetDistrictsByIDSRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type GetDistrictsByIDSResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Names         []string               `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDistrictsByIDSResponse) Reset() {
	*x = GetDistrictsByIDSResponse{}
	mi := &file_location_location_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDistrictsByIDSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDistrictsByIDSResponse) ProtoMessage() {}

func (x *GetDistrictsByIDSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_location_location_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDistrictsByIDSResponse.ProtoReflect.Descriptor instead.
func (*GetDistrictsByIDSResponse) Descriptor() ([]byte, []int) {
	return file_location_location_proto_rawDescGZIP(), []int{1}
}

func (x *GetDistrictsByIDSResponse) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

type GetCityByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCityByIDRequest) Reset() {
	*x = GetCityByIDRequest{}
	mi := &file_location_location_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCityByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCityByIDRequest) ProtoMessage() {}

func (x *GetCityByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_location_location_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCityByIDRequest.ProtoReflect.Descriptor instead.
func (*GetCityByIDRequest) Descriptor() ([]byte, []int) {
	return file_location_location_proto_rawDescGZIP(), []int{2}
}

func (x *GetCityByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetCityByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCityByIDResponse) Reset() {
	*x = GetCityByIDResponse{}
	mi := &file_location_location_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCityByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCityByIDResponse) ProtoMessage() {}

func (x *GetCityByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_location_location_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCityByIDResponse.ProtoReflect.Descriptor instead.
func (*GetCityByIDResponse) Descriptor() ([]byte, []int) {
	return file_location_location_proto_rawDescGZIP(), []int{3}
}

func (x *GetCityByIDResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CheckCityRequestByID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckCityRequestByID) Reset() {
	*x = CheckCityRequestByID{}
	mi := &file_location_location_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckCityRequestByID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckCityRequestByID) ProtoMessage() {}

func (x *CheckCityRequestByID) ProtoReflect() protoreflect.Message {
	mi := &file_location_location_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckCityRequestByID.ProtoReflect.Descriptor instead.
func (*CheckCityRequestByID) Descriptor() ([]byte, []int) {
	return file_location_location_proto_rawDescGZIP(), []int{4}
}

func (x *CheckCityRequestByID) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CheckCityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckCityResponse) Reset() {
	*x = CheckCityResponse{}
	mi := &file_location_location_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckCityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckCityResponse) ProtoMessage() {}

func (x *CheckCityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_location_location_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckCityResponse.ProtoReflect.Descriptor instead.
func (*CheckCityResponse) Descriptor() ([]byte, []int) {
	return file_location_location_proto_rawDescGZIP(), []int{5}
}

func (x *CheckCityResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type CheckDistrictRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CityId        string                 `protobuf:"bytes,1,opt,name=city_id,json=cityId,proto3" json:"city_id,omitempty"`
	DistrictId    string                 `protobuf:"bytes,2,opt,name=district_id,json=districtId,proto3" json:"district_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckDistrictRequest) Reset() {
	*x = CheckDistrictRequest{}
	mi := &file_location_location_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckDistrictRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckDistrictRequest) ProtoMessage() {}

func (x *CheckDistrictRequest) ProtoReflect() protoreflect.Message {
	mi := &file_location_location_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckDistrictRequest.ProtoReflect.Descriptor instead.
func (*CheckDistrictRequest) Descriptor() ([]byte, []int) {
	return file_location_location_proto_rawDescGZIP(), []int{6}
}

func (x *CheckDistrictRequest) GetCityId() string {
	if x != nil {
		return x.CityId
	}
	return ""
}

func (x *CheckDistrictRequest) GetDistrictId() string {
	if x != nil {
		return x.DistrictId
	}
	return ""
}

type CheckDistrictResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckDistrictResponse) Reset() {
	*x = CheckDistrictResponse{}
	mi := &file_location_location_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckDistrictResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckDistrictResponse) ProtoMessage() {}

func (x *CheckDistrictResponse) ProtoReflect() protoreflect.Message {
	mi := &file_location_location_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckDistrictResponse.ProtoReflect.Descriptor instead.
func (*CheckDistrictResponse) Descriptor() ([]byte, []int) {
	return file_location_location_proto_rawDescGZIP(), []int{7}
}

func (x *CheckDistrictResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

var File_location_location_proto protoreflect.FileDescriptor

const file_location_location_proto_rawDesc = "" +
	"\n" +
	"\x17location/location.proto\x12\blocation\",\n" +
	"\x18GetDistrictsByIDSRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\"1\n" +
	"\x19GetDistrictsByIDSResponse\x12\x14\n" +
	"\x05names\x18\x01 \x03(\tR\x05names\"$\n" +
	"\x12GetCityByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\")\n" +
	"\x13GetCityByIDResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"&\n" +
	"\x14CheckCityRequestByID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"+\n" +
	"\x11CheckCityResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\"P\n" +
	"\x14CheckDistrictRequest\x12\x17\n" +
	"\acity_id\x18\x01 \x01(\tR\x06cityId\x12\x1f\n" +
	"\vdistrict_id\x18\x02 \x01(\tR\n" +
	"districtId\"/\n" +
	"\x15CheckDistrictResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists2\xdb\x02\n" +
	"\x0fLocationService\x12L\n" +
	"\rCheckCityByID\x12\x1e.location.CheckCityRequestByID\x1a\x1b.location.CheckCityResponse\x12P\n" +
	"\rCheckDistrict\x12\x1e.location.CheckDistrictRequest\x1a\x1f.location.CheckDistrictResponse\x12\\\n" +
	"\x11GetDistrictsByIDS\x12\".location.GetDistrictsByIDSRequest\x1a#.location.GetDistrictsByIDSResponse\x12J\n" +
	"\vGetCityByID\x12\x1c.location.GetCityByIDRequest\x1a\x1d.location.GetCityByIDResponseB\vZ\t/locationb\x06proto3"

var (
	file_location_location_proto_rawDescOnce sync.Once
	file_location_location_proto_rawDescData []byte
)

func file_location_location_proto_rawDescGZIP() []byte {
	file_location_location_proto_rawDescOnce.Do(func() {
		file_location_location_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_location_location_proto_rawDesc), len(file_location_location_proto_rawDesc)))
	})
	return file_location_location_proto_rawDescData
}

var file_location_location_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_location_location_proto_goTypes = []any{
	(*GetDistrictsByIDSRequest)(nil),  // 0: location.GetDistrictsByIDSRequest
	(*GetDistrictsByIDSResponse)(nil), // 1: location.GetDistrictsByIDSResponse
	(*GetCityByIDRequest)(nil),        // 2: location.GetCityByIDRequest
	(*GetCityByIDResponse)(nil),       // 3: location.GetCityByIDResponse
	(*CheckCityRequestByID)(nil),      // 4: location.CheckCityRequestByID
	(*CheckCityResponse)(nil),         // 5: location.CheckCityResponse
	(*CheckDistrictRequest)(nil),      // 6: location.CheckDistrictRequest
	(*CheckDistrictResponse)(nil),     // 7: location.CheckDistrictResponse
}
var file_location_location_proto_depIdxs = []int32{
	4, // 0: location.LocationService.CheckCityByID:input_type -> location.CheckCityRequestByID
	6, // 1: location.LocationService.CheckDistrict:input_type -> location.CheckDistrictRequest
	0, // 2: location.LocationService.GetDistrictsByIDS:input_type -> location.GetDistrictsByIDSRequest
	2, // 3: location.LocationService.GetCityByID:input_type -> location.GetCityByIDRequest
	5, // 4: location.LocationService.CheckCityByID:output_type -> location.CheckCityResponse
	7, // 5: location.LocationService.CheckDistrict:output_type -> location.CheckDistrictResponse
	1, // 6: location.LocationService.GetDistrictsByIDS:output_type -> location.GetDistrictsByIDSResponse
	3, // 7: location.LocationService.GetCityByID:output_type -> location.GetCityByIDResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_location_location_proto_init() }
func file_location_location_proto_init() {
	if File_location_location_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_location_location_proto_rawDesc), len(file_location_location_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_location_location_proto_goTypes,
		DependencyIndexes: file_location_location_proto_depIdxs,
		MessageInfos:      file_location_location_proto_msgTypes,
	}.Build()
	File_location_location_proto = out.File
	file_location_location_proto_goTypes = nil
	file_location_location_proto_depIdxs = nil
}
