// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: location/location.proto

package location

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckCityRequestByID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckCityRequestByID) Reset() {
	*x = CheckCityRequestByID{}
	mi := &file_location_location_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckCityRequestByID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckCityRequestByID) ProtoMessage() {}

func (x *CheckCityRequestByID) ProtoReflect() protoreflect.Message {
	mi := &file_location_location_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckCityRequestByID.ProtoReflect.Descriptor instead.
func (*CheckCityRequestByID) Descriptor() ([]byte, []int) {
	return file_location_location_proto_rawDescGZIP(), []int{0}
}

func (x *CheckCityRequestByID) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CheckCityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckCityResponse) Reset() {
	*x = CheckCityResponse{}
	mi := &file_location_location_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckCityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckCityResponse) ProtoMessage() {}

func (x *CheckCityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_location_location_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckCityResponse.ProtoReflect.Descriptor instead.
func (*CheckCityResponse) Descriptor() ([]byte, []int) {
	return file_location_location_proto_rawDescGZIP(), []int{1}
}

func (x *CheckCityResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type CheckDistrictRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CityId        string                 `protobuf:"bytes,1,opt,name=city_id,json=cityId,proto3" json:"city_id,omitempty"`
	DistrictId    string                 `protobuf:"bytes,2,opt,name=district_id,json=districtId,proto3" json:"district_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckDistrictRequest) Reset() {
	*x = CheckDistrictRequest{}
	mi := &file_location_location_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckDistrictRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckDistrictRequest) ProtoMessage() {}

func (x *CheckDistrictRequest) ProtoReflect() protoreflect.Message {
	mi := &file_location_location_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckDistrictRequest.ProtoReflect.Descriptor instead.
func (*CheckDistrictRequest) Descriptor() ([]byte, []int) {
	return file_location_location_proto_rawDescGZIP(), []int{2}
}

func (x *CheckDistrictRequest) GetCityId() string {
	if x != nil {
		return x.CityId
	}
	return ""
}

func (x *CheckDistrictRequest) GetDistrictId() string {
	if x != nil {
		return x.DistrictId
	}
	return ""
}

type CheckDistrictResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckDistrictResponse) Reset() {
	*x = CheckDistrictResponse{}
	mi := &file_location_location_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckDistrictResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckDistrictResponse) ProtoMessage() {}

func (x *CheckDistrictResponse) ProtoReflect() protoreflect.Message {
	mi := &file_location_location_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckDistrictResponse.ProtoReflect.Descriptor instead.
func (*CheckDistrictResponse) Descriptor() ([]byte, []int) {
	return file_location_location_proto_rawDescGZIP(), []int{3}
}

func (x *CheckDistrictResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type GetUserLocationByUserIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserLocationByUserIDRequest) Reset() {
	*x = GetUserLocationByUserIDRequest{}
	mi := &file_location_location_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserLocationByUserIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserLocationByUserIDRequest) ProtoMessage() {}

func (x *GetUserLocationByUserIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_location_location_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserLocationByUserIDRequest.ProtoReflect.Descriptor instead.
func (*GetUserLocationByUserIDRequest) Descriptor() ([]byte, []int) {
	return file_location_location_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserLocationByUserIDRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UserLocationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	ZipCode       int32                  `protobuf:"varint,4,opt,name=zip_code,json=zipCode,proto3" json:"zip_code,omitempty"`
	PlateCode     int32                  `protobuf:"varint,5,opt,name=plate_code,json=plateCode,proto3" json:"plate_code,omitempty"`
	Districts     []*DistrictResponse    `protobuf:"bytes,6,rep,name=districts,proto3" json:"districts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLocationResponse) Reset() {
	*x = UserLocationResponse{}
	mi := &file_location_location_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLocationResponse) ProtoMessage() {}

func (x *UserLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_location_location_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLocationResponse.ProtoReflect.Descriptor instead.
func (*UserLocationResponse) Descriptor() ([]byte, []int) {
	return file_location_location_proto_rawDescGZIP(), []int{5}
}

func (x *UserLocationResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserLocationResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserLocationResponse) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *UserLocationResponse) GetZipCode() int32 {
	if x != nil {
		return x.ZipCode
	}
	return 0
}

func (x *UserLocationResponse) GetPlateCode() int32 {
	if x != nil {
		return x.PlateCode
	}
	return 0
}

func (x *UserLocationResponse) GetDistricts() []*DistrictResponse {
	if x != nil {
		return x.Districts
	}
	return nil
}

type DistrictResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CityId        string                 `protobuf:"bytes,2,opt,name=city_id,json=cityId,proto3" json:"city_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,4,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DistrictResponse) Reset() {
	*x = DistrictResponse{}
	mi := &file_location_location_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DistrictResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DistrictResponse) ProtoMessage() {}

func (x *DistrictResponse) ProtoReflect() protoreflect.Message {
	mi := &file_location_location_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DistrictResponse.ProtoReflect.Descriptor instead.
func (*DistrictResponse) Descriptor() ([]byte, []int) {
	return file_location_location_proto_rawDescGZIP(), []int{6}
}

func (x *DistrictResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DistrictResponse) GetCityId() string {
	if x != nil {
		return x.CityId
	}
	return ""
}

func (x *DistrictResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DistrictResponse) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

var File_location_location_proto protoreflect.FileDescriptor

const file_location_location_proto_rawDesc = "" +
	"\n" +
	"\x17location/location.proto\x12\blocation\"&\n" +
	"\x14CheckCityRequestByID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"+\n" +
	"\x11CheckCityResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\"P\n" +
	"\x14CheckDistrictRequest\x12\x17\n" +
	"\acity_id\x18\x01 \x01(\tR\x06cityId\x12\x1f\n" +
	"\vdistrict_id\x18\x02 \x01(\tR\n" +
	"districtId\"/\n" +
	"\x15CheckDistrictResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\"9\n" +
	"\x1eGetUserLocationByUserIDRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xc2\x01\n" +
	"\x14UserLocationResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12\x19\n" +
	"\bzip_code\x18\x04 \x01(\x05R\azipCode\x12\x1d\n" +
	"\n" +
	"plate_code\x18\x05 \x01(\x05R\tplateCode\x128\n" +
	"\tdistricts\x18\x06 \x03(\v2\x1a.location.DistrictResponseR\tdistricts\"c\n" +
	"\x10DistrictResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\acity_id\x18\x02 \x01(\tR\x06cityId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x04 \x01(\tR\x04slug2\x96\x02\n" +
	"\x0fLocationService\x12L\n" +
	"\rCheckCityByID\x12\x1e.location.CheckCityRequestByID\x1a\x1b.location.CheckCityResponse\x12P\n" +
	"\rCheckDistrict\x12\x1e.location.CheckDistrictRequest\x1a\x1f.location.CheckDistrictResponse\x12c\n" +
	"\x17GetUserLocationByUserID\x12(.location.GetUserLocationByUserIDRequest\x1a\x1e.location.UserLocationResponseB\vZ\t/locationb\x06proto3"

var (
	file_location_location_proto_rawDescOnce sync.Once
	file_location_location_proto_rawDescData []byte
)

func file_location_location_proto_rawDescGZIP() []byte {
	file_location_location_proto_rawDescOnce.Do(func() {
		file_location_location_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_location_location_proto_rawDesc), len(file_location_location_proto_rawDesc)))
	})
	return file_location_location_proto_rawDescData
}

var file_location_location_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_location_location_proto_goTypes = []any{
	(*CheckCityRequestByID)(nil),           // 0: location.CheckCityRequestByID
	(*CheckCityResponse)(nil),              // 1: location.CheckCityResponse
	(*CheckDistrictRequest)(nil),           // 2: location.CheckDistrictRequest
	(*CheckDistrictResponse)(nil),          // 3: location.CheckDistrictResponse
	(*GetUserLocationByUserIDRequest)(nil), // 4: location.GetUserLocationByUserIDRequest
	(*UserLocationResponse)(nil),           // 5: location.UserLocationResponse
	(*DistrictResponse)(nil),               // 6: location.DistrictResponse
}
var file_location_location_proto_depIdxs = []int32{
	6, // 0: location.UserLocationResponse.districts:type_name -> location.DistrictResponse
	0, // 1: location.LocationService.CheckCityByID:input_type -> location.CheckCityRequestByID
	2, // 2: location.LocationService.CheckDistrict:input_type -> location.CheckDistrictRequest
	4, // 3: location.LocationService.GetUserLocationByUserID:input_type -> location.GetUserLocationByUserIDRequest
	1, // 4: location.LocationService.CheckCityByID:output_type -> location.CheckCityResponse
	3, // 5: location.LocationService.CheckDistrict:output_type -> location.CheckDistrictResponse
	5, // 6: location.LocationService.GetUserLocationByUserID:output_type -> location.UserLocationResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_location_location_proto_init() }
func file_location_location_proto_init() {
	if File_location_location_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_location_location_proto_rawDesc), len(file_location_location_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_location_location_proto_goTypes,
		DependencyIndexes: file_location_location_proto_depIdxs,
		MessageInfos:      file_location_location_proto_msgTypes,
	}.Build()
	File_location_location_proto = out.File
	file_location_location_proto_goTypes = nil
	file_location_location_proto_depIdxs = nil
}
