// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: location/location.proto

package location

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckCityRequestByID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckCityRequestByID) Reset() {
	*x = CheckCityRequestByID{}
	mi := &file_location_location_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckCityRequestByID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckCityRequestByID) ProtoMessage() {}

func (x *CheckCityRequestByID) ProtoReflect() protoreflect.Message {
	mi := &file_location_location_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckCityRequestByID.ProtoReflect.Descriptor instead.
func (*CheckCityRequestByID) Descriptor() ([]byte, []int) {
	return file_location_location_proto_rawDescGZIP(), []int{0}
}

func (x *CheckCityRequestByID) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CheckCityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckCityResponse) Reset() {
	*x = CheckCityResponse{}
	mi := &file_location_location_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckCityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckCityResponse) ProtoMessage() {}

func (x *CheckCityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_location_location_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckCityResponse.ProtoReflect.Descriptor instead.
func (*CheckCityResponse) Descriptor() ([]byte, []int) {
	return file_location_location_proto_rawDescGZIP(), []int{1}
}

func (x *CheckCityResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type CheckDistrictRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CityId        string                 `protobuf:"bytes,1,opt,name=city_id,json=cityId,proto3" json:"city_id,omitempty"`
	DistrictId    string                 `protobuf:"bytes,2,opt,name=district_id,json=districtId,proto3" json:"district_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckDistrictRequest) Reset() {
	*x = CheckDistrictRequest{}
	mi := &file_location_location_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckDistrictRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckDistrictRequest) ProtoMessage() {}

func (x *CheckDistrictRequest) ProtoReflect() protoreflect.Message {
	mi := &file_location_location_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckDistrictRequest.ProtoReflect.Descriptor instead.
func (*CheckDistrictRequest) Descriptor() ([]byte, []int) {
	return file_location_location_proto_rawDescGZIP(), []int{2}
}

func (x *CheckDistrictRequest) GetCityId() string {
	if x != nil {
		return x.CityId
	}
	return ""
}

func (x *CheckDistrictRequest) GetDistrictId() string {
	if x != nil {
		return x.DistrictId
	}
	return ""
}

type CheckDistrictResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckDistrictResponse) Reset() {
	*x = CheckDistrictResponse{}
	mi := &file_location_location_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckDistrictResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckDistrictResponse) ProtoMessage() {}

func (x *CheckDistrictResponse) ProtoReflect() protoreflect.Message {
	mi := &file_location_location_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckDistrictResponse.ProtoReflect.Descriptor instead.
func (*CheckDistrictResponse) Descriptor() ([]byte, []int) {
	return file_location_location_proto_rawDescGZIP(), []int{3}
}

func (x *CheckDistrictResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

var File_location_location_proto protoreflect.FileDescriptor

const file_location_location_proto_rawDesc = "" +
	"\n" +
	"\x17location/location.proto\x12\blocation\"&\n" +
	"\x14CheckCityRequestByID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"+\n" +
	"\x11CheckCityResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\"P\n" +
	"\x14CheckDistrictRequest\x12\x17\n" +
	"\acity_id\x18\x01 \x01(\tR\x06cityId\x12\x1f\n" +
	"\vdistrict_id\x18\x02 \x01(\tR\n" +
	"districtId\"/\n" +
	"\x15CheckDistrictResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists2\xb1\x01\n" +
	"\x0fLocationService\x12L\n" +
	"\rCheckCityByID\x12\x1e.location.CheckCityRequestByID\x1a\x1b.location.CheckCityResponse\x12P\n" +
	"\rCheckDistrict\x12\x1e.location.CheckDistrictRequest\x1a\x1f.location.CheckDistrictResponseB2Z0github.com/ozdemirmurat2000/takas-proto/locationb\x06proto3"

var (
	file_location_location_proto_rawDescOnce sync.Once
	file_location_location_proto_rawDescData []byte
)

func file_location_location_proto_rawDescGZIP() []byte {
	file_location_location_proto_rawDescOnce.Do(func() {
		file_location_location_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_location_location_proto_rawDesc), len(file_location_location_proto_rawDesc)))
	})
	return file_location_location_proto_rawDescData
}

var file_location_location_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_location_location_proto_goTypes = []any{
	(*CheckCityRequestByID)(nil),  // 0: location.CheckCityRequestByID
	(*CheckCityResponse)(nil),     // 1: location.CheckCityResponse
	(*CheckDistrictRequest)(nil),  // 2: location.CheckDistrictRequest
	(*CheckDistrictResponse)(nil), // 3: location.CheckDistrictResponse
}
var file_location_location_proto_depIdxs = []int32{
	0, // 0: location.LocationService.CheckCityByID:input_type -> location.CheckCityRequestByID
	2, // 1: location.LocationService.CheckDistrict:input_type -> location.CheckDistrictRequest
	1, // 2: location.LocationService.CheckCityByID:output_type -> location.CheckCityResponse
	3, // 3: location.LocationService.CheckDistrict:output_type -> location.CheckDistrictResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_location_location_proto_init() }
func file_location_location_proto_init() {
	if File_location_location_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_location_location_proto_rawDesc), len(file_location_location_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_location_location_proto_goTypes,
		DependencyIndexes: file_location_location_proto_depIdxs,
		MessageInfos:      file_location_location_proto_msgTypes,
	}.Build()
	File_location_location_proto = out.File
	file_location_location_proto_goTypes = nil
	file_location_location_proto_depIdxs = nil
}
